### ISSUE TITLE
Split of measurement inconsistent

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/DCKit#17]
Splitting the attached measurement with DCKit 0.12.4 into two smaller files (e. g. with 90 events) causes the new files to have wrong event counts in the fluorescence traces, they still have the same length as the original file

![DCKit_error_event_count](https://user-images.githubusercontent.com/75362246/111613862-43ce9180-87df-11eb-9c68-e5844f120368.PNG)
[example_data.zip](https://github.com/ZELLMECHANIK-DRESDEN/DCKit/files/6163348/example_data.zip)

**Comment by paulmueller** [comment]
The root of this issue is in dclab. I am investigating. At least this does not affect compression or conversion from tdms to rtdc.

**Comment by paulmueller** [comment]
This is actually a regression in dclab 0.32.2 and affects:
- dclab>=0.32.2,<=0.33.0
- DCKit>=0.12.3,<=0.12.5
- Shape-Out>=2.5.0,<=2.6.0

**Comment by paulmueller** [comment]
This also affects you if you were converting very old .tdms data to .rtdc with DCKit or dclab. Very old means that "video frame offset = 1" (or not set) in para.ini.
