### ISSUE TITLE
Error loading data (probably related to #21)

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/DCKit#22]
Shape-Out 2.9.2

Related to #21 

I have a raw, unprocessed .rtdc file acquired with Shape-In 2.3.3.54. When I change the sample name of that .rtdc file with DCKit 0.12.17, acknowledge the error described in #21, then click on File->Clear measurements, but not closing DCKit, and then try to open that same file in Shape-Out, I get the following error message:
![Shape_out_2-9-2_loading_data_fails](https://user-images.githubusercontent.com/75362246/148928224-26b11d09-2225-4d22-9fa7-7eeab9ff6011.PNG)

**Comment by paulmueller** [comment]
I like that part ``èrror message = 'No error'``. Can you please point me to an example file?

**Comment by paulmueller** [comment]
This is because dclab.RTDCWriter did not properly close the HDF5 file (even in a context). This is fixed in dclab 0.39.10.
