### ISSUE TITLE
Compressed RTDC-files do not contain temporary features (anc. or plugin features)

### ISSUE THREAD

**Issue by maxschloegel** [ZELLMECHANIK-DRESDEN/DCKit#24]
When compressing RTDC files that contain temporary features, like ancillary or plugin features, the compressed files will not include those features. This is true for the  RTDC-dataset, but also for the raw HDF5-Dataset.
This seems to stem from the following:
DCKit uses the `dclab` cli-command `compress` which in turn uses `ds.export.hdf5`. For this function the features need to be defined which should be included in the exported dataset. These features are set to `features_innate` by default and hence do not contain the temporary features.

**Comment by paulmueller** [comment]
One solution would be to specifically ask the user whether he would like to keep these specific features "in general". This can then be a DCKit settings entry (so it is remembered). At every start, DCKit would then register the features as temporary features which should in principle make this work.
