### ISSUE TITLE
v0.4.1 does not run on MPL computers

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/DCKit#3]
We cannot install version 0.4.1 on any MPL computer. We tried several. Installation itself runs without error but launching the app causes the error message "Failed to execute script DCKit". Version 0.3.0 runs just fine on my machine and others also did not seem to have any problems.

![image](https://user-images.githubusercontent.com/19806005/72986049-a0a30780-3de7-11ea-8f46-592a5b29bad0.png)

**Comment by felix-r** [comment]
I also cannot install it using pip. I get the following error: 

![image](https://user-images.githubusercontent.com/19806005/72986615-e4e2d780-3de8-11ea-8c0c-6470ce409562.png)

**Comment by paulmueller** [comment]
Thanks for reporting. If you install via pip, could you try via ``pip install --user dckit``?

**Comment by paulmueller** [comment]
Should be fixed with 0.4.2.

**Comment by felix-r** [comment]
Version 0.4.2 works on my machine. Thanks
