### ISSUE TITLE
Question: Error to update metadata, what's the integrity check?

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/DCKit#7]
Hi,
I wanted to change the sample name and run index of measurements I accidentally saved in the wrong sample folder.  I thought, I could do this under the button "update metadata" but I just get the error message "Nothing to do!". If this means I have to select a measurement first then I don't know how to do it because clicking on the sample before gives the same message. The integrity check failed, I'll attach a screenshot with the dialog box. What does that mean? I use DCKit 0.8.0.
![image](https://user-images.githubusercontent.com/19806005/75768236-3f564880-5d44-11ea-9293-d44c336c26fc.png)

**Comment by paulmueller** [comment]
Did you edit the sample name before clicking "Update metadata"? (BTW You should only be able to update the sample name, not the run index.)

Which software/version did you use to create the file? Could you please point me to the data on the group share?

**Comment by felix-r** [comment]
I used ShapeIn v2.1.1.0. I changed the filename before opening it in DCKit. Does this cause problems?

**Comment by paulmueller** [comment]
No, changing the filename should not cause any problems. I am wondering where the "def" comes from.

**Comment by felix-r** [comment]
Sorry, forgot to put the path. The file is on the share under:
\\mplshare\guck_division\Data\RTDC\200302_Felix_HL60_beads\HL60_w_beads\20um\standardRTDC

**Comment by paulmueller** [comment]
@phidahl  I beliefe the "def" feature is supposed to be "deform". Is this a bug in Shape-In?

**Comment by paulmueller** [comment]
@felix-r I can edit the sample name here on Linux just fine. Please make sure that you edit the sample name **before** hitting "Update metadata".

**Comment by felix-r** [comment]
> @felix-r I can edit the sample name here on Linux just fine. Please make sure that you edit the sample name **before** hitting "Update metadata".

Alright this actually worked. Thanks.
