### ISSUE TITLE
Splitting big datasets into multiple files

### ISSUE THREAD

**Issue by sdespina** [ZELLMECHANIK-DRESDEN/DCKit#8]
Would it be possible to split a dataset that is 30GB size into 3 smaller ones to make the processing easier?
Or if we could apply certain gates to such a dataset and then save it as a new file that will be smaller in size?

**Comment by paulmueller** [comment]
I have created a new issue #9 for the gating/filtering part. Dataset splitting will come with dclab 0.28.0. I am currently incorporating it in DCKit.
